### ISSUE TITLE
Comparison with Heracles.ts

### ISSUE THREAD

**Issue by alexkreidler** [wikibus/Alcaeus#165]
Hi, I'm really interested in using Hydra in a new project, but I'm having trouble figuring out the best frontend client library.

I've found this project and [Heracles.ts](https://github.com/HydraCG/Heracles.ts), the "Reference implementation of a Hydra client in TypeScript."

I don't really have too much time to figure out the technical differences -- on first glance they seem very similar.

I'd really appreciate a quick explanation of the major differences. Thannks!

ping @tpluscode @alien-mcl

**Comment by tpluscode** [comment]
Hello @alexkreidler. Thank you for your interest in Alcaeus

On the functional level, both packages should offer a similar feature set. The devil might be in minutiae details which I came across while building APIs (such as handling redirects, headers, etc). I cannot comment on how Heracles.ts compares in edge cases.

Thats said, I am fairly advanced redesigning the internals of Alcaeus so that it is lighter on dependencies and better integrates with [RDF/JS](https://rdf.js.org) libraries. The memory model in the 1.0 version of the client will be a [`Dataset`](https://rdf.js.org/dataset-spec/#datasetcore-interface) object.

**Comment by alien-mcl** [comment]
@alexkreidler, [Heracles.ts](https://github.com/HydraCG/Heracles.ts) is (as you've already figured it out), a reference client - it means that it is how a client (a generic one at least) should work to be compliant with the specification. It is also maintained by the hydra community and for community.

From technical point of view - I've never used Alcaeus, thus I'm unable to point direct differences. Heracles was designed to hide most of the RDF related quirks from the developer, thus it uses an internal structural data model similar to what you and other developers may know from everyday work. There is also a [Heracles.net](https://github.com/HydraCG/Heracles.net) for .net platform that provides same development experience as these are currently maintained simultaneously.

**Comment by alexkreidler** [comment]
Thanks so much, I really appreciate this!
